# Generated by Django 5.2.9 on 2025-12-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
