# Generated by Django 6.0 on 2025-12-28 16:20

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=movies.models.poster_upload_path),
        ),
    ]
